backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"     # ที่เก็บไฟล์จริงใน repo
public_folder: "/img/uploads"   # path เรียกใช้งานไฟล์

site_url: "https://your-site.netlify.app"

collections:
  - name: "posts"
    label: "บทความ"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "หัวข้อ", name: "title", widget: "string" }
      - { label: "วันที่", name: "date", widget: "datetime" }
      - { label: "เนื้อหา", name: "body", widget: "markdown" }
